name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Set Git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Add Hugging Face remote
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git remote add hf https://miraarif:$HF_TOKEN@huggingface.co/spaces/miraarif/Sql_Chatbot

      - name: Rebase Hugging Face changes (prefer GitHub version)
        run: |
          git fetch hf main
          git rebase -X theirs hf/main

      - name: Push to Hugging Face
        run: git push hf main
